using System;

namespace System.ComponentModel.DataAnnotations.ContentConstraints {

  /// <summary>
  ///  Defines, that a Property contains String-Content.
  ///  This Attribute is ONLY VALID when placed on a Property of Type of STRING
  ///  or, if a compatible serialization kind is used, on a Property of Type of LONG (Int64) !
  /// </summary>
  [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
  public class RequireSerializedContentAttribute : Attribute {

    /// <summary>
    ///  Defines, that a Property contains Serialized-Content.
    ///  This Attribute is ONLY VALID when placed on a Property of Type of STRING
    ///  or, if a compatible serialization kind is used, on a Property of Type of LONG (Int64) !
    /// </summary>
    /// <param name="disallowEmptyString"></param>
    /// <param name="serializationKind">Selects one of the wellknown serialization kinds (see Enum)</param>
    public RequireSerializedContentAttribute(
      bool disallowEmptyString,
      SerializationKind serializationKind 
    ) {

    }

  }

  /// <summary>
  /// Wellknown kinds of serialization that  
  /// </summary>
  public enum SerializationKind {
    ///<summary> a byte-array, encoded in base64 format  </summary>
    BytesAsBase64,

    ///<summary> a byte-array, encoded in hexadecimal format (LOWER casing!) </summary>
    BytesAsHex,

    ///<summary> serveral string-Tags, separated by whitespace-chars </summary>
    SpaceSeparatedTags,

    ///<summary> serveral string-Tags, separated by semicolon-chars </summary>
    SemicolonSeparatedTags,

    ///<summary> serveral string-Tags, separated by comma-chars </summary>
    CommaSeparatedTags,

    ///<summary> Content, which is compatible with the SmartStandars "TupleSerializer" </summary>
    TupleSerializer,

    ///<summary> 
    ///Content, which is compatible with the SmartStandars "EncodedToken" > an UNSIGNED LONG NUMBER 
    ///(Note: content with this SerializationKind is usually stored within a property of Type LONG - 
    ///for which the usage of the 'RequireSerializedContentAttribute' is explicitely allowed!)
    ///</summary>
    EncodedToken,

    ///<summary>
    ///Content which is an UNSIGNED LONG, representing a TIMESTAMP,
    ///generated by the SmartStandars "Snowflake44" algorithm > an UNSIGNED LONG NUMBER 
    ///(Note: content with this SerializationKind is usually stored within a property of Type LONG - 
    ///for which the usage of the 'RequireSerializedContentAttribute' is explicitely allowed!)
    ///</summary>
    Snowflake44,

    ///<summary> Content must be in JSON format! </summary>
    JsonStructure,

    ///<summary> Content must be in XML format! </summary>
    XmlStructure,

    ///<summary> Content must be in MARKDOWN format! </summary>
    Markdown
  }

}
